// lib/constants.ts
export const CATEGORIES = [
  "종합베스트",
  "시/에세이", 
  "TOEIC/TOEFL",
  "가정생활",
  "건강",
  "경제경영",
  "과학",
  "기술/컴퓨터",
  "만화",
  "서양도서",
  "소설",
  "시",
  "아동",
  "아동만화",
  "에세이",
  "여행",
  "역사/문화",
  "예술",
  "외국소설",
  "외국어",
  "요리",
  "유아",
  "인문",
  "일본도서",
  "자기계발",
  "정치사회",
  "종교",
  "청소년",
  "취미/스포츠",
  "한국소설"
];

// 영업점 데이터
export interface Store {
  code: string;
  name: string;
}

export const STORES: Store[] = [
  { code: "001", name: "광화문점" },
  { code: "002", name: "대전점" },
  { code: "003", name: "원그로브점" },
  { code: "004", name: "대구점" },
  { code: "005", name: "부산점" },
  { code: "013", name: "부천점" },
  { code: "015", name: "강남점" },
  { code: "023", name: "건대스타시티점" },
  { code: "024", name: "세종점" },
  { code: "025", name: "인천점" },
  { code: "028", name: "창원점" },
  { code: "029", name: "잠실점" },
  { code: "031", name: "전주점" },
  { code: "033", name: "목동점" },
  { code: "034", name: "천안점" },
  { code: "036", name: "영등포점" },
  { code: "038", name: "일산점" },
  { code: "039", name: "울산점" },
  { code: "041", name: "동대문점" },
  { code: "042", name: "송도점" },
  { code: "043", name: "해운대 팝업스토어" },
  { code: "045", name: "센텀시티점" },
  { code: "046", name: "은평점" },
  { code: "047", name: "분당점" },
  { code: "048", name: "칠곡점" },
  { code: "049", name: "합정점" },
  { code: "052", name: "광교월드스퀘어점" },
  { code: "056", name: "청량리점" },
  { code: "057", name: "평촌점" },
  { code: "058", name: "가든파이브점" },
  { code: "059", name: "경성대부경대점" },
  { code: "064", name: "서울역점" },
  { code: "065", name: "거제 팝업스토어" },
  { code: "066", name: "신도림디큐브시티점" },
  { code: "067", name: "KH본부(음반,문구)" },
  { code: "068", name: "수유점" },
  { code: "069", name: "판교점" },
  { code: "070", name: "광교점" },
  { code: "071", name: "수원팝업스토어" },
  { code: "072", name: "서울대교내서점" },
  { code: "074", name: "이화여대교내서점" },
  { code: "075", name: "포항공대교내서점" },
  { code: "077", name: "전북대교내서점" },
  { code: "078", name: "광명팝업스토어" },
  { code: "081", name: "고척팝업스토어" },
  { code: "082", name: "신채널1" },
  { code: "083", name: "신채널2" },
  { code: "084", name: "신채널3" },
  { code: "085", name: "신채널4" },
  { code: "087", name: "광주상무점" },
  { code: "090", name: "천호점" },
];